"""数据集模块 — 30 部电影（含中文名、年份、简介）。

查询优先走 SQLAlchemy，不可用时回退 Python dict。
"""

# ==============================
# 电影数据
# title_en, title_cn, year, genres, tags, description
# ==============================

MOVIES = {
    1: {"title_en": "The Shawshank Redemption", "title_cn": "肖申克的救赎", "year": 1994,
        "genres": ["Drama"], "tags": ["prison", "hope", "friendship", "escape", "redemption"],
        "description": "A banker convicted of murder forms an enduring friendship and finds redemption through acts of common decency inside a brutal prison system."},
    2: {"title_en": "The Godfather", "title_cn": "教父", "year": 1972,
        "genres": ["Crime", "Drama"], "tags": ["mafia", "family", "power", "betrayal", "revenge"],
        "description": "The aging patriarch of an organized crime dynasty transfers control to his reluctant youngest son, chronicling the Corleone family's rise and near fall."},
    3: {"title_en": "The Dark Knight", "title_cn": "蝙蝠侠：黑暗骑士", "year": 2008,
        "genres": ["Action", "Crime", "Drama"], "tags": ["batman", "joker", "chaos", "vigilante", "sacrifice"],
        "description": "Batman faces the Joker, a criminal mastermind who plunges Gotham into anarchy and forces the hero to cross ethical lines."},
    4: {"title_en": "Pulp Fiction", "title_cn": "低俗小说", "year": 1994,
        "genres": ["Crime", "Drama"], "tags": ["nonlinear", "hitman", "dialogue", "dark comedy", "intertwined"],
        "description": "The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine in four tales of violence and redemption."},
    5: {"title_en": "Forrest Gump", "title_cn": "阿甘正传", "year": 1994,
        "genres": ["Drama", "Romance"], "tags": ["running", "history", "love", "destiny", "innocence"],
        "description": "A simple but kind-hearted Alabama man witnesses and unwittingly influences major historical events while pursuing his childhood love."},
    6: {"title_en": "Inception", "title_cn": "盗梦空间", "year": 2010,
        "genres": ["Action", "Sci-Fi"], "tags": ["dream", "heist", "layers", "reality", "subconscious"],
        "description": "A skilled thief who steals secrets from dreams is offered a chance to have his past cleared if he can plant an idea instead—inception."},
    7: {"title_en": "The Matrix", "title_cn": "黑客帝国", "year": 1999,
        "genres": ["Action", "Sci-Fi"], "tags": ["simulation", "kungfu", "reality", "AI", "awakening"],
        "description": "A computer hacker learns that his entire reality is a simulated construct and joins a rebellion against its machine overlords."},
    8: {"title_en": "Interstellar", "title_cn": "星际穿越", "year": 2014,
        "genres": ["Sci-Fi", "Drama"], "tags": ["space", "time", "family", "black hole", "sacrifice"],
        "description": "A team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival on a dying Earth."},
    9: {"title_en": "Fight Club", "title_cn": "搏击俱乐部", "year": 1999,
        "genres": ["Drama"], "tags": ["identity", "fight", "twist", "consumerism", "insomnia"],
        "description": "An insomniac office worker forms an underground fight club with a charismatic soap maker, spiraling into anarchy and self-destruction."},
    10: {"title_en": "Goodfellas", "title_cn": "好家伙", "year": 1990,
        "genres": ["Crime", "Drama"], "tags": ["mafia", "gangster", "betrayal", "rise and fall", "true story"],
        "description": "The true story of Henry Hill, a half-Irish half-Sicilian who climbs the ranks of the New York mafia before his world comes crashing down."},
    11: {"title_en": "Toy Story", "title_cn": "玩具总动员", "year": 1995,
        "genres": ["Animation", "Comedy"], "tags": ["toys", "friendship", "pixar", "jealousy", "teamwork"],
        "description": "A cowboy doll is threatened when a new space action figure arrives, and their rivalry turns into an unlikely friendship."},
    12: {"title_en": "Finding Nemo", "title_cn": "海底总动员", "year": 2003,
        "genres": ["Animation", "Adventure"], "tags": ["ocean", "father", "journey", "family", "courage"],
        "description": "A timid clownfish embarks on an epic journey across the ocean to rescue his son who has been captured by a diver."},
    13: {"title_en": "Up", "title_cn": "飞屋环游记", "year": 2009,
        "genres": ["Animation", "Adventure"], "tags": ["balloons", "elderly", "adventure", "loss", "friendship"],
        "description": "A 78-year-old balloon salesman ties thousands of balloons to his house and flies to South America, accompanied by a young stowaway."},
    14: {"title_en": "WALL-E", "title_cn": "机器人总动员", "year": 2008,
        "genres": ["Animation", "Sci-Fi"], "tags": ["robot", "earth", "love", "environment", "loneliness"],
        "description": "A lonely waste-collecting robot on an abandoned Earth falls in love and embarks on a space journey that decides humanity's fate."},
    15: {"title_en": "The Lion King", "title_cn": "狮子王", "year": 1994,
        "genres": ["Animation", "Drama"], "tags": ["lion", "betrayal", "circle of life", "revenge", "redemption"],
        "description": "A young lion prince is exiled by his murderous uncle and must find the courage to reclaim his rightful throne."},
    16: {"title_en": "Gladiator", "title_cn": "角斗士", "year": 2000,
        "genres": ["Action", "Drama"], "tags": ["rome", "revenge", "arena", "honor", "general"],
        "description": "A betrayed Roman general is reduced to slavery and rises through the gladiatorial ranks to avenge his murdered family and emperor."},
    17: {"title_en": "Braveheart", "title_cn": "勇敢的心", "year": 1995,
        "genres": ["Action", "Drama"], "tags": ["scotland", "freedom", "battle", "rebellion", "sacrifice"],
        "description": "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from English tyranny."},
    18: {"title_en": "Saving Private Ryan", "title_cn": "拯救大兵瑞恩", "year": 1998,
        "genres": ["Action", "Drama"], "tags": ["war", "sacrifice", "brothers", "WW2", "mission"],
        "description": "A squad of U.S. soldiers goes behind enemy lines to retrieve a paratrooper whose three brothers have been killed in action."},
    19: {"title_en": "Schindler's List", "title_cn": "辛德勒的名单", "year": 1993,
        "genres": ["Drama", "History"], "tags": ["holocaust", "rescue", "humanity", "WW2", "sacrifice"],
        "description": "A German industrialist gradually realizes the horror of the Holocaust and saves over a thousand Jewish refugees by employing them in his factories."},
    20: {"title_en": "The Silence of the Lambs", "title_cn": "沉默的羔羊", "year": 1991,
        "genres": ["Crime", "Thriller"], "tags": ["serial killer", "fbi", "psychopath", "mind game", "cannibalism"],
        "description": "A young FBI cadet seeks the help of an imprisoned cannibalistic psychiatrist to catch another serial killer."},
    21: {"title_en": "Se7en", "title_cn": "七宗罪", "year": 1995,
        "genres": ["Crime", "Thriller"], "tags": ["sin", "detective", "dark", "serial killer", "moral"],
        "description": "Two detectives hunt a serial killer who uses the seven deadly sins as his modus operandi, leading to a shocking conclusion."},
    22: {"title_en": "The Usual Suspects", "title_cn": "非常嫌疑犯", "year": 1995,
        "genres": ["Crime", "Thriller"], "tags": ["twist", "heist", "mystery", "interrogation", "deception"],
        "description": "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began with five criminals meeting in a seemingly random police lineup."},
    23: {"title_en": "Léon: The Professional", "title_cn": "这个杀手不太冷", "year": 1994,
        "genres": ["Crime", "Drama"], "tags": ["hitman", "girl", "revenge", "unlikely bond", "redemption"],
        "description": "A 12-year-old girl forms an unlikely relationship with a professional hitman after her family is murdered, and learns his trade."},
    24: {"title_en": "Spirited Away", "title_cn": "千与千寻", "year": 2001,
        "genres": ["Animation", "Adventure"], "tags": ["spirits", "bathhouse", "courage", "growth", "greed"],
        "description": "A young girl wanders into a spirit world where she must work in a bathhouse to free her parents who have been turned into pigs."},
    25: {"title_en": "Princess Mononoke", "title_cn": "幽灵公主", "year": 1997,
        "genres": ["Animation", "Adventure"], "tags": ["nature", "spirits", "war", "balance", "coexistence"],
        "description": "A young prince becomes embroiled in a struggle between forest gods and a mining colony, exploring the conflict between progress and nature."},
    26: {"title_en": "La La Land", "title_cn": "爱乐之城", "year": 2016,
        "genres": ["Romance", "Musical"], "tags": ["jazz", "dreams", "los angeles", "sacrifice", "ambition"],
        "description": "A jazz pianist and an aspiring actress fall in love while pursuing their dreams in Los Angeles, but success may pull them apart."},
    27: {"title_en": "Titanic", "title_cn": "泰坦尼克号", "year": 1997,
        "genres": ["Romance", "Drama"], "tags": ["ship", "love", "tragedy", "class divide", "sacrifice"],
        "description": "A poor artist and a wealthy aristocrat fall in love aboard the ill-fated maiden voyage of the RMS Titanic."},
    28: {"title_en": "The Notebook", "title_cn": "恋恋笔记本", "year": 2004,
        "genres": ["Romance", "Drama"], "tags": ["memory", "love", "tears", "Alzheimer's", "destiny"],
        "description": "An elderly man reads a love story from his notebook to a fellow nursing home resident, recounting a passionate summer romance that spans decades."},
    29: {"title_en": "Amélie", "title_cn": "天使爱美丽", "year": 2001,
        "genres": ["Romance", "Comedy"], "tags": ["paris", "quirky", "kindness", "whimsical", "introvert"],
        "description": "A shy Parisian waitress decides to anonymously improve the lives of those around her while grappling with her own isolation."},
    30: {"title_en": "Whiplash", "title_cn": "爆裂鼓手", "year": 2014,
        "genres": ["Drama", "Music"], "tags": ["drum", "teacher", "obsession", "perfection", "abuse"],
        "description": "A promising young drummer enrolls at a cutthroat music conservatory where an abusive instructor will stop at nothing to realize a student's potential."},
    31: {"title_en": "The Prestige", "title_cn": "致命魔术", "year": 2006,
        "genres": ["Drama", "Mystery", "Thriller"], "tags": ["magic", "rivalry", "twist", "sacrifice", "obsession"],
        "description": "Two rival magicians in Victorian London engage in a bitter feud, pushing the boundaries of science and illusion with devastating consequences."},
    32: {"title_en": "Memento", "title_cn": "记忆碎片", "year": 2000,
        "genres": ["Mystery", "Thriller"], "tags": ["memory", "nonlinear", "revenge", "twist", "identity"],
        "description": "A man with short-term memory loss uses notes and tattoos to hunt for his wife's killer in this groundbreaking nonlinear thriller."},
    33: {"title_en": "The Departed", "title_cn": "无间道风云", "year": 2006,
        "genres": ["Crime", "Drama", "Thriller"], "tags": ["undercover", "mafia", "betrayal", "police", "identity"],
        "description": "An undercover cop and a mole in the police force race to identify each other while infiltrating a Boston crime syndicate."},
    34: {"title_en": "Eternal Sunshine of the Spotless Mind", "title_cn": "暖暖内含光", "year": 2004,
        "genres": ["Drama", "Romance", "Sci-Fi"], "tags": ["memory", "love", "breakup", "regret", "dreamlike"],
        "description": "A couple undergoes a medical procedure to erase each other from their memories after a painful breakup, discovering love may transcend memory."},
    35: {"title_en": "The Green Mile", "title_cn": "绿里奇迹", "year": 1999,
        "genres": ["Drama", "Fantasy"], "tags": ["prison", "miracle", "death row", "compassion", "supernatural"],
        "description": "A death row prison guard discovers that one of his inmates possesses a mysterious healing gift, forcing him to confront justice and humanity."},
    36: {"title_en": "Casablanca", "title_cn": "卡萨布兰卡", "year": 1942,
        "genres": ["Drama", "Romance", "War"], "tags": ["sacrifice", "love", "war", "morocco", "classic"],
        "description": "An American expatriate in WWII Casablanca must choose between his love for a woman and helping her resistance-leader husband escape the Nazis."},
    37: {"title_en": "12 Angry Men", "title_cn": "十二怒汉", "year": 1957,
        "genres": ["Drama", "Crime"], "tags": ["jury", "justice", "debate", "prejudice", "single room"],
        "description": "A lone juror tries to convince his eleven colleagues that a murder case is not as clear-cut as it seems in this tense courtroom drama."},
    38: {"title_en": "City of God", "title_cn": "上帝之城", "year": 2002,
        "genres": ["Crime", "Drama"], "tags": ["favela", "gang", "coming of age", "photography", "brazil"],
        "description": "A young man growing up in the violent slums of Rio de Janeiro pursues photography as his escape from the cycle of crime and poverty."},
    39: {"title_en": "The Shining", "title_cn": "闪灵", "year": 1980,
        "genres": ["Horror", "Thriller"], "tags": ["hotel", "madness", "supernatural", "isolation", "family"],
        "description": "A family becomes the winter caretakers of an isolated hotel where the father descends into madness, influenced by the hotel's dark supernatural forces."},
    40: {"title_en": "Alien", "title_cn": "异形", "year": 1979,
        "genres": ["Horror", "Sci-Fi"], "tags": ["space", "monster", "survival", "spaceship", "isolation"],
        "description": "A commercial spaceship crew investigates a distress signal on a desolate planet and brings aboard a deadly alien creature that hunts them one by one."},
    41: {"title_en": "Blade Runner", "title_cn": "银翼杀手", "year": 1982,
        "genres": ["Sci-Fi", "Noir"], "tags": ["android", "dystopia", "identity", "rain", "future"],
        "description": "In a dystopian future Los Angeles, a burned-out cop hunts down rogue replicants—bioengineered beings indistinguishable from humans—while questioning his own humanity."},
    42: {"title_en": "The Truman Show", "title_cn": "楚门的世界", "year": 1998,
        "genres": ["Drama", "Comedy"], "tags": ["reality", "surveillance", "escape", "media", "freedom"],
        "description": "An ordinary man discovers his entire life is a 24/7 reality TV show broadcast to millions, and he must find the courage to escape his manufactured world."},
    43: {"title_en": "A Beautiful Mind", "title_cn": "美丽心灵", "year": 2001,
        "genres": ["Drama", "Biography"], "tags": ["mathematics", "schizophrenia", "genius", "love", "struggle"],
        "description": "A brilliant mathematician struggles with schizophrenia while making groundbreaking contributions to game theory, supported by his devoted wife."},
    44: {"title_en": "Requiem for a Dream", "title_cn": "梦之安魂曲", "year": 2000,
        "genres": ["Drama"], "tags": ["addiction", "drugs", "descent", "hallucination", "tragedy"],
        "description": "Four individuals spiral into devastating drug addiction, each pursuing their version of the American dream through increasingly desperate means."},
    45: {"title_en": "Old Boy", "title_cn": "老男孩", "year": 2003,
        "genres": ["Action", "Mystery", "Thriller"], "tags": ["revenge", "imprisonment", "twist", "korea", "violence"],
        "description": "A man is inexplicably imprisoned for 15 years and then suddenly released, embarking on a brutal quest for vengeance and the truth behind his captivity."},
    46: {"title_en": "Parasite", "title_cn": "寄生虫", "year": 2019,
        "genres": ["Drama", "Thriller", "Comedy"], "tags": ["class", "inequality", "family", "deception", "korea"],
        "description": "A poor family cunningly infiltrates a wealthy household, leading to unexpected and violent consequences in this Oscar-winning social satire."},
    47: {"title_en": "The Social Network", "title_cn": "社交网络", "year": 2010,
        "genres": ["Drama", "Biography"], "tags": ["facebook", "betrayal", "lawsuit", "ambition", "startup"],
        "description": "The story of Mark Zuckerberg's creation of Facebook and the legal battles and broken friendships that followed his meteoric rise to power."},
    48: {"title_en": "Jaws", "title_cn": "大白鲨", "year": 1975,
        "genres": ["Thriller", "Adventure"], "tags": ["shark", "ocean", "survival", "fear", "beach"],
        "description": "A giant man-eating great white shark terrorizes a beach town, forcing the police chief, a marine biologist, and a grizzled fisherman to hunt it down."},
    49: {"title_en": "Jurassic Park", "title_cn": "侏罗纪公园", "year": 1993,
        "genres": ["Action", "Adventure", "Sci-Fi"], "tags": ["dinosaur", "island", "survival", "chaos", "genetics"],
        "description": "A billionaire creates a theme park of cloned dinosaurs on a remote island, but when the security systems fail, the prehistoric creatures run wild."},
    50: {"title_en": "The Lord of the Rings: The Fellowship of the Ring", "title_cn": "指环王：护戒使者", "year": 2001,
        "genres": ["Adventure", "Fantasy"], "tags": ["ring", "quest", "fellowship", "middle earth", "epic"],
        "description": "A young hobbit embarks on an epic quest to destroy a powerful ring and save Middle-earth from the Dark Lord Sauron."},
    51: {"title_en": "Star Wars: Episode IV - A New Hope", "title_cn": "星球大战4：新希望", "year": 1977,
        "genres": ["Action", "Adventure", "Sci-Fi"], "tags": ["space", "empire", "rebellion", "force", "hero's journey"],
        "description": "A young farm boy joins a rebellion against the evil Galactic Empire after discovering a mysterious message from a captive princess."},
    52: {"title_en": "Back to the Future", "title_cn": "回到未来", "year": 1985,
        "genres": ["Adventure", "Comedy", "Sci-Fi"], "tags": ["time travel", "teenager", "car", "past", "future"],
        "description": "A teenager is accidentally sent 30 years into the past in a time-traveling DeLorean and must ensure his parents fall in love to save his own existence."},
    53: {"title_en": "Indiana Jones and the Raiders of the Lost Ark", "title_cn": "夺宝奇兵", "year": 1981,
        "genres": ["Action", "Adventure"], "tags": ["archaeology", "nazi", "artifact", "quest", "snake"],
        "description": "An archaeology professor races against Nazi forces to find the legendary Ark of the Covenant before they can harness its supernatural power."},
    54: {"title_en": "The Terminator", "title_cn": "终结者", "year": 1984,
        "genres": ["Action", "Sci-Fi"], "tags": ["robot", "future", "assassin", "time travel", "survival"],
        "description": "A relentless cyborg assassin is sent back in time to kill the mother of the future resistance leader, while a soldier follows to protect her."},
    55: {"title_en": "Aliens", "title_cn": "异形2", "year": 1986,
        "genres": ["Action", "Horror", "Sci-Fi"], "tags": ["alien", "marines", "colony", "survival", "queen"],
        "description": "Ellen Ripley returns to the alien planet with a squad of colonial marines to investigate the loss of contact with a terraforming colony."},
    56: {"title_en": "The Thing", "title_cn": "怪形", "year": 1982,
        "genres": ["Horror", "Sci-Fi", "Mystery"], "tags": ["antarctic", "parasite", "paranoia", "isolation", "shape-shifter"],
        "description": "A research team in Antarctica is terrorized by a shape-shifting alien that can perfectly imitate any living organism, breeding extreme paranoia."},
    57: {"title_en": "Die Hard", "title_cn": "虎胆龙威", "year": 1988,
        "genres": ["Action", "Thriller"], "tags": ["terrorist", "skyscraper", "christmas", "hero", "hostage"],
        "description": "A New York cop single-handedly takes on a group of terrorists who have taken over a Los Angeles skyscraper during a Christmas party."},
    58: {"title_en": "Mad Max: Fury Road", "title_cn": "疯狂的麦克斯4：狂暴之路", "year": 2015,
        "genres": ["Action", "Adventure", "Sci-Fi"], "tags": ["post-apocalyptic", "car", "chase", "desert", "rebellion"],
        "description": "In a post-apocalyptic wasteland, a lone warrior joins forces with a rebel woman to escape a tyrannical warlord in an epic vehicular chase."},
    59: {"title_en": "The Grand Budapest Hotel", "title_cn": "布达佩斯大饭店", "year": 2014,
        "genres": ["Comedy", "Drama"], "tags": ["hotel", "murder", "nostalgia", "colorful", "europe"],
        "description": "The adventures of an eccentric concierge and his loyal lobby boy at a famous European hotel between the world wars, involving a stolen painting and a family fortune."},
    60: {"title_en": "No Country for Old Men", "title_cn": "老无所依", "year": 2007,
        "genres": ["Crime", "Drama", "Thriller"], "tags": ["drugs", "hitman", "money", "fate", "texas"],
        "description": "A hunter stumbles upon a drug deal gone wrong and takes a briefcase of cash, pursued by a relentless and philosophical hitman across the Texas landscape."},
    61: {"title_en": "There Will Be Blood", "title_cn": "血色将至", "year": 2007,
        "genres": ["Drama"], "tags": ["oil", "greed", "religion", "rivalry", "ambition"],
        "description": "The epic story of an ambitious oil prospector in early 20th century California whose ruthless pursuit of wealth pits him against a young preacher."},
    62: {"title_en": "A Clockwork Orange", "title_cn": "发条橙", "year": 1971,
        "genres": ["Crime", "Drama", "Sci-Fi"], "tags": ["violence", "conditioning", "dystopia", "free will", "controversial"],
        "description": "A violent young delinquent undergoes an experimental aversion therapy to cure his criminal tendencies, raising disturbing questions about free will."},
    63: {"title_en": "2001: A Space Odyssey", "title_cn": "2001太空漫游", "year": 1968,
        "genres": ["Sci-Fi", "Adventure"], "tags": ["space", "AI", "evolution", "monolith", "philosophical"],
        "description": "A journey from prehistoric times to the future follows humanity's evolution and a mysterious black monolith that influences human destiny, aided by the sentient computer HAL 9000."},
    64: {"title_en": "One Flew Over the Cuckoo's Nest", "title_cn": "飞越疯人院", "year": 1975,
        "genres": ["Drama"], "tags": ["mental asylum", "rebellion", "freedom", "nurse", "conformity"],
        "description": "A criminal feigns insanity to serve his sentence in a mental hospital, where he rallies the patients against the oppressive head nurse."},
    65: {"title_en": "Apocalypse Now", "title_cn": "现代启示录", "year": 1979,
        "genres": ["Drama", "War"], "tags": ["vietnam", "madness", "river", "jungle", "darkness"],
        "description": "A U.S. Army captain is sent on a dangerous mission into the Cambodian jungle to assassinate a renegade colonel who has set himself up as a god among local tribes."},
    66: {"title_en": "Chinatown", "title_cn": "唐人街", "year": 1974,
        "genres": ["Drama", "Mystery", "Thriller"], "tags": ["detective", "corruption", "water", "los angeles", "noir"],
        "description": "A private detective investigating an adultery case in 1930s Los Angeles uncovers a vast conspiracy involving the city's water supply and a powerful family."},
    67: {"title_en": "Taxi Driver", "title_cn": "出租车司机", "year": 1976,
        "genres": ["Crime", "Drama"], "tags": ["loneliness", "vigilante", "new york", "insomnia", "alienation"],
        "description": "A mentally unstable Vietnam War veteran works as a nighttime taxi driver in New York City, where his growing disgust with society drives him toward violent action."},
    68: {"title_en": "Vertigo", "title_cn": "迷魂记", "year": 1958,
        "genres": ["Mystery", "Romance", "Thriller"], "tags": ["obsession", "deception", "acrophobia", "detective", "identity"],
        "description": "A retired detective with a fear of heights is hired to follow a friend's wife, becoming dangerously obsessed with her in this Hitchcock masterpiece."},
    69: {"title_en": "Psycho", "title_cn": "惊魂记", "year": 1960,
        "genres": ["Horror", "Mystery", "Thriller"], "tags": ["motel", "murder", "shower", "mother", "psychopath"],
        "description": "A secretary on the run checks into a remote motel run by a young man under the domination of his mother, leading to one of cinema's most shocking twists."},
    70: {"title_en": "The Good, the Bad and the Ugly", "title_cn": "黄金三镖客", "year": 1966,
        "genres": ["Western", "Adventure"], "tags": ["cowboy", "gold", "civil war", "duel", "bounty"],
        "description": "Three gunslingers compete to find a buried fortune in Confederate gold during the chaos of the American Civil War in this definitive spaghetti western."},
    71: {"title_en": "Seven Samurai", "title_cn": "七武士", "year": 1954,
        "genres": ["Action", "Drama"], "tags": ["samurai", "village", "protection", "japan", "bandit"],
        "description": "A poor farming village hires seven masterless samurai to defend them against a band of marauding bandits in this epic Japanese classic."},
    72: {"title_en": "Coco", "title_cn": "寻梦环游记", "year": 2017,
        "genres": ["Animation", "Adventure", "Family"], "tags": ["music", "family", "death", "mexico", "remembrance"],
        "description": "A young aspiring musician enters the Land of the Dead to find his great-great-grandfather and unlock the truth about his family's ban on music."},
    73: {"title_en": "Inside Out", "title_cn": "头脑特工队", "year": 2015,
        "genres": ["Animation", "Comedy", "Family"], "tags": ["emotion", "mind", "growing up", "memory", "pixar"],
        "description": "The five personified emotions inside a young girl's mind navigate her life when her family moves to a new city, exploring the complexity of growing up."},
    74: {"title_en": "Howl's Moving Castle", "title_cn": "哈尔的移动城堡", "year": 2004,
        "genres": ["Animation", "Adventure", "Fantasy"], "tags": ["magic", "castle", "war", "curse", "love"],
        "description": "A young hat-maker is cursed by a witch and transformed into an old woman, finding refuge in the magical moving castle of a mysterious wizard."},
    75: {"title_en": "My Neighbor Totoro", "title_cn": "龙猫", "year": 1988,
        "genres": ["Animation", "Family", "Fantasy"], "tags": ["forest", "spirit", "childhood", "sister", "nature"],
        "description": "Two young sisters move to the countryside and befriend magical forest spirits, including the gentle giant Totoro, while their mother recovers in a hospital."},
    76: {"title_en": "Grave of the Fireflies", "title_cn": "萤火虫之墓", "year": 1988,
        "genres": ["Animation", "Drama", "War"], "tags": ["siblings", "survival", "WW2", "tragedy", "japan"],
        "description": "Two orphaned siblings struggle to survive in post-WWII Japan, confronting the brutal realities of war, starvation, and loss in this devastating animated film."},
    77: {"title_en": "Your Name", "title_cn": "你的名字。", "year": 2016,
        "genres": ["Animation", "Drama", "Fantasy", "Romance"], "tags": ["body swap", "comet", "time", "fate", "japan"],
        "description": "Two teenagers discover they are swapping bodies intermittently and embark on a quest to find each other across time and space before a catastrophic comet strike."},
    78: {"title_en": "The Dark Knight Rises", "title_cn": "蝙蝠侠：黑暗骑士崛起", "year": 2012,
        "genres": ["Action", "Drama", "Thriller"], "tags": ["batman", "bane", "sacrifice", "gotham", "redemption"],
        "description": "Eight years after taking the fall for Harvey Dent's crimes, Batman is forced out of exile when a masked terrorist named Bane brings Gotham to its knees."},
    79: {"title_en": "The Avengers", "title_cn": "复仇者联盟", "year": 2012,
        "genres": ["Action", "Adventure", "Sci-Fi"], "tags": ["superhero", "team", "alien", "battle", "marvel"],
        "description": "Earth's mightiest heroes must assemble to stop an alien invasion led by the trickster god Loki, who seeks to conquer Earth with a powerful cosmic artifact."},
    80: {"title_en": "Logan", "title_cn": "金刚狼3：殊死一战", "year": 2017,
        "genres": ["Action", "Drama", "Sci-Fi"], "tags": ["wolverine", "aging", "protect", "mutant", "western"],
        "description": "In a near future where mutants are nearly extinct, an aging Wolverine cares for a dementia-stricken Professor X while protecting a young mutant from dark forces."},
    81: {"title_en": "Get Out", "title_cn": "逃出绝命镇", "year": 2017,
        "genres": ["Horror", "Mystery", "Thriller"], "tags": ["racism", "conspiracy", "hypnosis", "social commentary", "twist"],
        "description": "A young African-American man visits his white girlfriend's family estate and uncovers a disturbing secret beneath their welcoming facade."},
    82: {"title_en": "Gone Girl", "title_cn": "消失的爱人", "year": 2014,
        "genres": ["Drama", "Mystery", "Thriller"], "tags": ["marriage", "disappearance", "media", "twist", "revenge"],
        "description": "When his wife disappears on their fifth anniversary, a man becomes the prime suspect—but nothing is as it seems in this twisty psychological thriller."},
    83: {"title_en": "Arrival", "title_cn": "降临", "year": 2016,
        "genres": ["Drama", "Mystery", "Sci-Fi"], "tags": ["alien", "language", "time", "memory", "communication"],
        "description": "A linguist is recruited by the military to communicate with mysterious alien spacecraft that have landed around the world, discovering their language reshapes her perception of time."},
    84: {"title_en": "Blade Runner 2049", "title_cn": "银翼杀手2049", "year": 2017,
        "genres": ["Drama", "Mystery", "Sci-Fi"], "tags": ["android", "memory", "identity", "dystopia", "future"],
        "description": "A young blade runner discovers a long-buried secret that could plunge what remains of society into chaos, leading him to track down a legendary former blade runner."},
    85: {"title_en": "The Revenant", "title_cn": "荒野猎人", "year": 2015,
        "genres": ["Action", "Adventure", "Drama"], "tags": ["survival", "revenge", "bear", "wilderness", "betrayal"],
        "description": "A frontiersman on a fur trading expedition is mauled by a bear and left for dead by his companions, then embarks on a brutal quest for survival and revenge."},
    86: {"title_en": "Her", "title_cn": "她", "year": 2013,
        "genres": ["Drama", "Romance", "Sci-Fi"], "tags": ["AI", "love", "loneliness", "operating system", "relationship"],
        "description": "A lonely writer develops an intimate relationship with an advanced artificial intelligence operating system, exploring the nature of love and consciousness."},
    87: {"title_en": "Shutter Island", "title_cn": "禁闭岛", "year": 2010,
        "genres": ["Mystery", "Thriller"], "tags": ["asylum", "detective", "twist", "mental", "island"],
        "description": "A U.S. Marshal investigates the disappearance of a patient from a hospital for the criminally insane on a remote island, confronting disturbing truths about his own reality."},
    88: {"title_en": "Donnie Darko", "title_cn": "死亡幻觉", "year": 2001,
        "genres": ["Drama", "Mystery", "Sci-Fi"], "tags": ["time travel", "rabbit", "teenager", "apocalypse", "cult"],
        "description": "A troubled teenager is haunted by visions of a giant rabbit that manipulates him to commit a series of crimes after he narrowly escapes a bizarre accident."},
    89: {"title_en": "E.T. the Extra-Terrestrial", "title_cn": "外星人E.T.", "year": 1982,
        "genres": ["Adventure", "Family", "Sci-Fi"], "tags": ["alien", "friendship", "bicycle", "childhood", "escape"],
        "description": "A lonely boy befriends a gentle alien stranded on Earth and helps him find his way home while evading government agents."},
    90: {"title_en": "Groundhog Day", "title_cn": "土拨鼠之日", "year": 1993,
        "genres": ["Comedy", "Drama", "Fantasy"], "tags": ["time loop", "redemption", "weather", "self-improvement", "romance"],
        "description": "A cynical weatherman finds himself trapped in a time loop, reliving the same day over and over until he learns to become a better person."},
    91: {"title_en": "The Sixth Sense", "title_cn": "第六感", "year": 1999,
        "genres": ["Drama", "Mystery", "Thriller"], "tags": ["ghost", "psychologist", "twist", "child", "supernatural"],
        "description": "A child psychologist tries to help a young boy who claims he can see and communicate with dead people, leading to one of cinema's most famous plot twists."},
    92: {"title_en": "Good Will Hunting", "title_cn": "心灵捕手", "year": 1997,
        "genres": ["Drama"], "tags": ["genius", "therapy", "boston", "mathematics", "blue collar"],
        "description": "A self-taught mathematical genius working as a janitor at MIT is discovered and forced to confront his past trauma with the help of an unconventional therapist."},
    93: {"title_en": "Django Unchained", "title_cn": "被解救的姜戈", "year": 2012,
        "genres": ["Drama", "Western"], "tags": ["slavery", "revenge", "bounty hunter", "plantation", "rescue"],
        "description": "A freed slave teams up with a German bounty hunter to rescue his wife from a brutal Mississippi plantation owner in this stylized revenge western."},
    94: {"title_en": "Prisoners", "title_cn": "囚徒", "year": 2013,
        "genres": ["Crime", "Drama", "Mystery", "Thriller"], "tags": ["kidnapping", "detective", "torture", "desperation", "father"],
        "description": "When two young girls go missing, a desperate father takes matters into his own hands while a detective pursues every lead in this dark and gripping thriller."},
    95: {"title_en": "The Wolf of Wall Street", "title_cn": "华尔街之狼", "year": 2013,
        "genres": ["Biography", "Comedy", "Crime", "Drama"], "tags": ["money", "drugs", "excess", "stock market", "fbi"],
        "description": "The outrageous true story of Jordan Belfort's rise to wealth as a stockbroker and his spectacular fall involving crime, corruption, and the federal government."},
    96: {"title_en": "Inglourious Basterds", "title_cn": "无耻混蛋", "year": 2009,
        "genres": ["Adventure", "Drama", "War"], "tags": ["nazi", "revenge", "WW2", "alternate history", "cinema"],
        "description": "A group of Jewish-American soldiers known as the Basterds spread fear among the Nazis in occupied France while a cinema owner plots her own revenge."},
    97: {"title_en": "Life Is Beautiful", "title_cn": "美丽人生", "year": 1997,
        "genres": ["Comedy", "Drama", "Romance", "War"], "tags": ["holocaust", "father", "imagination", "sacrifice", "love"],
        "description": "A Jewish-Italian father uses his imagination and humor to shield his young son from the horrors of a Nazi concentration camp."},
    98: {"title_en": "Dead Poets Society", "title_cn": "死亡诗社", "year": 1989,
        "genres": ["Drama"], "tags": ["teacher", "poetry", "inspiration", "conformity", "tragedy"],
        "description": "An unconventional English teacher inspires his students at a conservative prep school to seize the day and pursue their passions, with tragic consequences."},
    99: {"title_en": "The Pursuit of Happyness", "title_cn": "当幸福来敲门", "year": 2006,
        "genres": ["Drama", "Biography"], "tags": ["homelessness", "father", "perseverance", "dream", "success"],
        "description": "A struggling salesman takes custody of his young son and pursues a life-changing internship at a prestigious brokerage firm while facing homelessness."},
    100: {"title_en": "Joker", "title_cn": "小丑", "year": 2019,
        "genres": ["Crime", "Drama", "Thriller"], "tags": ["mental illness", "society", "descent", "clown", "rebellion"],
        "description": "A mentally troubled failed comedian descends into madness and becomes the criminal mastermind known as the Joker in this gritty character study."},
}

# ==============================
# 用户数据（简化，仅 REST API demo 用）
# ==============================

USERS = {
    "u1": {"name": "Alice"},
    "u2": {"name": "Bob"},
}

# ==============================
# 查询函数
# ==============================

_db_available: bool | None = None


def _use_db() -> bool:
    global _db_available
    if _db_available is None:
        try:
            from database import SessionLocal
            from models.movie import Movie
            db = SessionLocal()
            count = db.query(Movie).count()
            db.close()
            _db_available = count > 0
        except Exception:
            _db_available = False
    return _db_available


def get_all_movies() -> list[dict]:
    if _use_db():
        from database import SessionLocal
        from crud.movie import get_all_movies as _db_get_all
        db = SessionLocal()
        movies = _db_get_all(db)
        db.close()
        return [m.to_dict() for m in movies]
    return [{"movie_id": mid, **info} for mid, info in MOVIES.items()]


def get_movie_details(movie_ids: list[int]) -> list[dict]:
    if _use_db():
        from database import SessionLocal
        from crud.movie import get_movies_by_ids
        db = SessionLocal()
        movies = get_movies_by_ids(db, movie_ids)
        db.close()
        return [m.to_dict() for m in movies]
    results = []
    for mid in movie_ids:
        if mid in MOVIES:
            results.append({"movie_id": mid, **MOVIES[mid]})
    return results


def get_user_info(user_id: str) -> dict | None:
    return USERS.get(user_id)
